# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Team.destroy_all
Player.destroy_all
User.destroy_all
Roster.destroy_all

Player.create!(name: "Christian McCaffrey", team: "CAR", position: 'RB', default_price: 71)
Player.create!(name: "Saquon Barkley", team: "NYG", position: 'RB', default_price: 63)
Player.create!(name: "Ezekiel Elliott", team: "DAL", position: 'RB', default_price: 61)
Player.create!(name: "Dalvin Cook", team: "MIN", position: 'RB', default_price: 58)
Player.create!(name: "Alvin Kamara", team: "NO", position: 'RB', default_price: 53)
Player.create!(name: "Derrick Henry", team: "TEN", position: 'RB', default_price: 51)
Player.create!(name: "Michael Thomas", team: "NO", position: 'WR', default_price: 50)
Player.create!(name: "Aaron Jones", team: "GB", position: 'RB', default_price: 42)
Player.create!(name: "Kenyan Drake", team: "ARI", position: 'RB', default_price: 42)
Player.create!(name: "Miles Sanders", team: "PHI", position: 'RB', default_price: 41)
Player.create!(name: "Davante Adams", team: "GB", position: 'WR', default_price: 41)
Player.create!(name: "Joe Mixon", team: "CIN", position: 'RB', default_price: 40)
Player.create!(name: "Nick Chubb", team: "CLE", position: 'RB', default_price: 39)
Player.create!(name: "Josh Jacobs", team: "LV", position: 'RB', default_price: 38)
Player.create!(name: "Austin Ekeler", team: "LAC", position: 'RB', default_price: 37)
Player.create!(name: "Julio Jones", team: "ATL", position: 'WR', default_price: 37)
Player.create!(name: "Todd Gurley", team: "ATL", position: 'RB', default_price: 35)
Player.create!(name: "Tyreek Hill", team: "KC", position: 'WR', default_price: 38)
Player.create!(name: "Travic Kelce", team: "KC", position: 'TE', default_price: 35)
Player.create!(name: "Chris Carson", team: "SEA", position: 'RB', default_price: 33)
Player.create!(name: "DeAndre Hopkins", team: "ARI", position: 'WR', default_price: 32)
Player.create!(name: "David Johnson", team: "HOU", position: 'RB', default_price: 31)
Player.create!(name: "Le'Veon Bell", team: "NYJ", position: 'RB', default_price: 31)
Player.create!(name: "Leonard Fournette", team: "JAC", position: 'RB', default_price: 31)
Player.create!(name: "George Kittle", team: "SF", position: 'TE', default_price: 30)
Player.create!(name: "Lamar Jackson", team: "BAL", position: 'QB', default_price: 29)
Player.create!(name: "Clyde Edwards-Helaire", team: "KC", position: 'RB', default_price: 28)
Player.create!(name: "Chris Godwin", team: "TB", position: 'WR', default_price: 28)
Player.create!(name: "Melvin Gordon", team: "DEN", position: 'RB', default_price: 27)
Player.create!(name: "Patrick Mahomes", team: "KC", position: 'QB', default_price: 26)
Player.create!(name: "Kenny Golladay", team: "DET", position: 'WR', default_price: 25)
Player.create!(name: "Mike Evans", team: "TB", position: 'WR', default_price: 25)
Player.create!(name: "James Conner", team: "PIT", position: 'RB', default_price: 24)
Player.create!(name: "Adam Thielen", team: "MIN", position: 'WR', default_price: 24)
Player.create!(name: "Cooper Kupp", team: "LAR", position: 'WR', default_price: 23)
Player.create!(name: "JuJu Smith-Schuster", team: "PIT", position: 'WR', default_price: 22)
Player.create!(name: "Robert Woods", team: "LAR", position: 'WR', default_price: 22)
Player.create!(name: "Amari Cooper", team: "DAL", position: 'WR', default_price: 22)
Player.create!(name: "D.J. Moore", team: "CAR", position: 'WR', default_price: 22)
Player.create!(name: "David Montgomery", team: "CHI", position: 'RB', default_price: 21)
Player.create!(name: "Odell Beckham Jr.", team: "CLE", position: 'WR', default_price: 21)
Player.create!(name: "Jonathan Taylor", team: "IND", position: 'RB', default_price: 20)
Player.create!(name: "Devin Singletary", team: "BUF", position: 'RB', default_price: 20)
Player.create!(name: "Mark Ingram II", team: "BAL", position: 'RB', default_price: 20)
Player.create!(name: "Allen Robinson", team: "CHI", position: 'WR', default_price: 20)
Player.create!(name: "Zach Ertz", team: "PHI", position: 'TE', default_price: 20)
Player.create!(name: "Dak Prescott", team: "DAL", position: 'QB', default_price: 19)
Player.create!(name: "Tyler Lockett", team: "SEA", position: 'WR', default_price: 19)
# Player.create!(name: "Calvin Ridley", team: "ATL", position: 'WR', default_price: 19)
# Player.create!(name: "A.J. Brown", team: "TEN", position: 'WR', default_price: 19)
# Player.create!(name: "Keenan Allen", team: "LAC", position: 'WR', default_price: 19)
# Player.create!(name: "Mark Andrews", team: "BAL", position: 'TE', default_price: 19)
# Player.create!(name: "D'Andre Swift", team: "DET", position: 'RB', default_price: 18)
# Player.create!(name: "Kareem Hunt", team: "CLE", position: 'RB', default_price: 17)
# Player.create!(name: "Courtland Sutton", team: "DEN", position: 'WR', default_price: 17)
# Player.create!(name: "Darren Waller", team: "LV", position: 'TE', default_price: 17)
# Player.create!(name: "Deshaun Watson", team: "HOU", position: 'QB', default_price: 16)
# Player.create!(name: "Raheem Mostert", team: "SF", position: 'RB', default_price: 16)
# Player.create!(name: "T.Y. Hilton", team: "IND", position: 'WR', default_price: 16)
# Player.create!(name: "Russell Wilson", team: "SEA", position: 'QB', default_price: 15)
# Player.create!(name: "Terry McLaurin", team: "WAS", position: 'WR', default_price: 15)
# Player.create!(name: "Cam Akers", team: "LAR", position: 'RB', default_price: 14)
# Player.create!(name: "Ronald Jones", team: "TB", position: 'RB', default_price: 14)
# Player.create!(name: "DeVante Parker", team: "MIA", position: 'WR', default_price: 14)
# Player.create!(name: "Kyler Murray", team: "ARI", position: 'QB', default_price: 13)
# Player.create!(name: "Kerryon Johnson", team: "DET", position: 'RB', default_price: 13)
# Player.create!(name: "Derrius Guice", team: "WAS", position: 'RB', default_price: 13)
# Player.create!(name: "Jarvis Landry", team: "CLE", position: 'WR', default_price: 13)
# Player.create!(name: "Josh Allen", team: "BUF", position: 'QB', default_price: 12)
# Player.create!(name: "Tarik Cohen", team: "CHI", position: 'RB', default_price: 12)
# Player.create!(name: "A.J. Green", team: "CIN", position: 'WR', default_price: 12)
# Player.create!(name: "D.J. Chark", team: "JAC", position: 'WR', default_price: 12)
# Player.create!(name: "Damien Williams", team: "KC", position: 'RB', default_price: 11)
# Player.create!(name: "James White", team: "NE", position: 'RB', default_price: 11)
# Player.create!(name: "Tevin Coleman", team: "SF", position: 'RB', default_price: 11)
# Player.create!(name: "D.K. Metcalf", team: "SEA", position: 'WR', default_price: 11)
# Player.create!(name: "Stefon Diggs", team: "BUF", position: 'WR', default_price: 11)
# Player.create!(name: "Evan Engram", team: "NYG", position: 'TE', default_price: 11)
# Player.create!(name: "Sony Michel", team: "NE", position: 'RB', default_price: 10)
# Player.create!(name: "Ke'Shawn Vaughn", team: "TB", position: 'RB', default_price: 10)
# Player.create!(name: "Jordan Howard", team: "MIA", position: 'RB', default_price: 10)
# Player.create!(name: "Matt Breida", team: "MIA", position: 'RB', default_price: 10)
# Player.create!(name: "Phillip Lindsay", team: "DEN", position: 'RB', default_price: 10)
# Player.create!(name: "Michael Gallup", team: "DAL", position: 'WR', default_price: 10)
# Player.create!(name: "Julian Edelman", team: "NE", position: 'WR', default_price: 10)
# Player.create!(name: "Matt Ryan", team: "ATL", position: 'QB', default_price: 9)
# Player.create!(name: "Marlon Mack", team: "IND", position: 'RB', default_price: 9)
# Player.create!(name: "Marquise Brown", team: "BAL", position: 'WR', default_price: 9)
# Player.create!(name: "Tyler Boyd", team: "CIN", position: 'WR', default_price: 9)
# Player.create!(name: "Tom Brady", team: "NE", position: 'QB', default_price: 8)
# Player.create!(name: "Marvin Jones", team: "DET", position: 'WR', default_price: 8)
# Player.create!(name: "Hunter Henry", team: "LAC", position: 'TE', default_price: 8)
# Player.create!(name: "Tyler Higbee", team: "LAR", position: 'TE', default_price: 8)
# Player.create!(name: "Jared Cook", team: "NO", position: 'TE', default_price: 8)
# Player.create!(name: "Drew Brees", team: "NO", position: 'QB', default_price: 7)
# Player.create!(name: "Latavius Murray", team: "NO", position: 'RB', default_price: 7)
# Player.create!(name: "Duke Johnson", team: "HOU", position: 'RB', default_price: 7)
# Player.create!(name: "Hayden Hurst", team: "ATL", position: 'TE', default_price: 7)
# Player.create!(name: "Aaron Rodgers", team: "GB", position: 'QB', default_price: 6)
# Player.create!(name: "J.K. Dobbins", team: "BAL", position: 'RB', default_price: 6)
# Player.create!(name: "Darrell Henderson", team: "LAR", position: 'RB', default_price: 6)
# Player.create!(name: "Diontae Johnson", team: "PIT", position: 'WR', default_price: 6)
# Player.create!(name: "Brandin Cooks", team: "HOU", position: 'WR', default_price: 6)
# Player.create!(name: "Carson Wentz", team: "PHI", position: 'QB', default_price: 5)
# Player.create!(name: "Zack Moss", team: "BUF", position: 'RB', default_price: 5)
# Player.create!(name: "Nyheim Hines", team: "IND", position: 'RB', default_price: 5)
# Player.create!(name: "Christian Kirk", team: "ARI", position: 'WR', default_price: 5)
# Player.create!(name: "Jamison Crowder", team: "NYJ", position: 'WR', default_price: 5)
# Player.create!(name: "Will Fuller", team: "HOU", position: 'WR', default_price: 5)
# Player.create!(name: "Sterling Shepard", team: "NYG", position: 'WR', default_price: 5)
# Player.create!(name: "Rob Gronkowski", team: "TB", position: 'TE', default_price: 10)
# Player.create!(name: "Noah Fant", team: "DEN", position: 'TE', default_price: 5)
# Player.create!(name: "Boston Scott", team: "PHI", position: 'RB', default_price: 4)
# Player.create!(name: "Tony Pollard", team: "DAL", position: 'RB', default_price: 4)
# Player.create!(name: "Golden Tate", team: "NYG", position: 'WR', default_price: 4)
# Player.create!(name: "Austin Hooper", team: "CLE", position: 'TE', default_price: 4)
# Player.create!(name: "Matthew Stafford", team: "DET", position: 'QB', default_price: 3)
# Player.create!(name: "Justin Jackson", team: "LAC", position: 'RB', default_price: 3)
# Player.create!(name: "Alexander Mattison", team: "MIN", position: 'RB', default_price: 3)
# Player.create!(name: "Darrynton Evans", team: "TEN", position: 'RB', default_price: 3)
# Player.create!(name: "Chase Edmonds", team: "ARI", position: 'RB', default_price: 3)
# Player.create!(name: "Antonio Gibson", team: "WAS", position: 'RB', default_price: 3)
# Player.create!(name: "Adrian Peterson", team: "WAS", position: 'RB', default_price: 3)
# Player.create!(name: "Jamaal Williams", team: "GB", position: 'RB', default_price: 3)
# Player.create!(name: "Emmanuel Sanders", team: "NO", position: 'WR', default_price: 3)
# Player.create!(name: "T.J. Hockenson", team: "DET", position: 'TE', default_price: 3)
# Player.create!(name: "Mike Gesicki", team: "MIA", position: 'TE', default_price: 3)
# Player.create!(name: "Jared Goff", team: "LAR", position: "QB", default_price: 2)
# Player.create!(name: "Cam Newton", team: "NE", position: "QB", default_price: 2)
# Player.create!(name: "Daniel Jones", team: "NYG", position: "QB", default_price: 2)
# Player.create!(name: "Jalen Richard", team: "LV", position: "RB", default_price: 2)
# Player.create!(name: "Ito Smith", team: "ATL", position: "RB", default_price: 2)
# Player.create!(name: "Mike Williams", team: "LAC", position: "WR", default_price: 2)
# Player.create!(name: "John Brown", team: "BUF", position: "WR", default_price: 2)
# Player.create!(name: "Preston Williams", team: "MIA", position: "WR", default_price: 2)
# Player.create!(name: "Anthony Miller", team: "CHI", position: "WR", default_price: 2)
# Player.create!(name: "Deebo Samuel", team: "SF", position: "WR", default_price: 2)
# Player.create!(name: "Darius Slayton", team: "NYG", position: "WR", default_price: 2)
# Player.create!(name: "Jalen Reagor", team: "PHI", position: "WR", default_price: 2)
# Player.create!(name: "Chris Herndon IV", team: "NYJ", position: "TE", default_price: 2)
# Player.create!(name: "Jack Doyle", team: "IND", position: "TE", default_price: 2)
# Player.create!(name: "Pittsburgh Steelers", team: "PIT", position: "DST", default_price: 2)
# Player.create!(name: "San Francisco 49ers", team: "SF", position: "DST", default_price: 2)
# Player.create!(name: "Los Angeles Rams", team: "LAR", position: "DST", default_price: 2)
# Player.create!(name: "New England Patriots", team: "NE", position: "DST", default_price: 2)
# Player.create!(name: "Ryan Tannehill", team: "TEN", position: "QB", default_price: 2)
# Player.create!(name: "Baker Mayfield", team: "CLE", position: "QB", default_price: 1)
# Player.create!(name: "Ben Roethlisberger", team: "PIT", position: "QB", default_price: 1)
# Player.create!(name: "Giovani Bernard", team: "CIN", position: "RB", default_price: 1)
# Player.create!(name: "Joshua Kelly", team: "LAC", position: "RB", default_price: 1)
# Player.create!(name: "A.J. Dillon", team: "GB", position: "RB", default_price: 1)
# Player.create!(name: "Chris Thompson", team: "JAC", position: "RB", default_price: 1)
# Player.create!(name: "Jerry Jeudy", team: "DEN", position: "WR", default_price: 5)
# Player.create!(name: "CeeDee Lamb", team: "DAL", position: "WR", default_price: 5)
# Player.create!(name: "Henry Ruggs III", team: "LV", position: "WR", default_price: 5)
# Player.create!(name: "Jonnu Smith", team: "TEN", position: "TE", default_price: 1)
# Player.create!(name: "Dallas Goedert", team: "PHI", position: "TE", default_price: 1)
# Player.create!(name: "Blake Jarwin", team: "DAL", position: "TE", default_price: 1)
# Player.create!(name: "Minnesota Vikings", team: "MIN", position: "DST", default_price: 2)
# Player.create!(name: "Baltimore Ravens", team: "BAL", position: "DST", default_price: 2)
# Player.create!(name: "Philadelphia Eagles", team: "PHI", position: "DST", default_price: 1)
# Player.create!(name: "New Orleans Saints", team: "NO", position: "DST", default_price: 1)
# Player.create!(name: "Kansas City Chiefs", team: "KC", position: "DST", default_price: 1)
# Player.create!(name: "Buffalo Bills", team: "BUF", position: "DST", default_price: 1)
# Player.create!(name: "Tampa Bay Buccaneers", team: "TB", position: "DST", default_price: 1)
# Player.create!(name: "Indianapolis Colts", team: "IND", position: "DST", default_price: 1)
# Player.create!(name: "Harrison Butker", team: "KC", position: "K", default_price: 2)
# Player.create!(name: "Will Lutz", team: "NO", position: "K", default_price: 2)
# Player.create!(name: "Justin Tucker", team: "BAL", position: "K", default_price: 2)
# Player.create!(name: "Greg Zuerlein", team: "DAL", position: "K", default_price: 2)
# Player.create!(name: "Robbie Gould", team: "SF", position: "K", default_price: 1)
# Player.create!(name: "Matt Prater", team: "DET", position: "K", default_price: 1)
# Player.create!(name: "Jake Elliott", team: "PHI", position: "K", default_price: 1)
# Player.create!(name: "Dan Bailey", team: "MIN", position: "K", default_price: 1)
# Player.create!(name: "Jason Myers", team: "SEA", position: "K", default_price: 1)
# Player.create!(name: "Brandon McManus", team: "DEN", position: "K", default_price: 1)
# Player.create!(name: "Younghoe Koo", team: "ATL", position: "K", default_price: 1)
# Player.create!(name: "Sam Sloman", team: "LAR", position: "K", default_price: 1)
# Player.create!(name: "Kirk Cousins", team: "MIN", position: "QB", default_price: 1)
# Player.create!(name: "Robby Anderson", team: "CAR", position: "WR", default_price: 1)
# Player.create!(name: "Curtis Samuel", team: "CAR", position: "WR", default_price: 1)
# Player.create!(name: "DeSean Jackson", team: "PHI", position: "WR", default_price: 1)
# Player.create!(name: "Sammy Watkins", team: "KC", position: "WR", default_price: 1)
# Player.create!(name: "Breshad Perriman", team: "NYJ", position: "WR", default_price: 0)
# Player.create!(name: "Matt Gay", team: "TB", position: "K", default_price: 1)
# Player.create!(name: "Austin Seibert", team: "CLE", position: "K", default_price: 0)
# Player.create!(name: "Chris Boswell", team: "PIT", position: "K", default_price: 0)
# Player.create!(name: "Zane Gonzalez", team: "ARI", position: "K", default_price: 0)
# Player.create!(name: "Mason Crosby", team: "GB", position: "K", default_price: 0)
# Player.create!(name: "Chase McLaughlin", team: "IND", position: "K", default_price: 0)
# Player.create!(name: "Justin Rohrwasser", team: "NE", position: "K", default_price: 0)
# Player.create!(name: "Seattle Seahawks", team: "SEA", position: "DST", default_price: 0)
# Player.create!(name: "Cleveland Browns", team: "CLE", position: "DST", default_price: 0)
# Player.create!(name: "Washington Football Team", team: "WAS", position: "DST", default_price: 0)
# Player.create!(name: "Carolina Panthers", team: "CAR", position: "DST", default_price: 0)
# Player.create!(name: "Denver Broncos", team: "DEN", position: "DST", default_price: 0)
# Player.create!(name: "Green Bay Packers", team: "GB", position: "DST", default_price: 0)
# Player.create!(name: "Jacksonville Jaguars", team: "JAC", position: "DST", default_price: 0)
# Player.create!(name: "Eric Ebron", team: "PIT", position: "TE", default_price: 0)
# Player.create!(name: "Houston Texans", team: "HOU", position: "DST", default_price: 0)
# Player.create!(name: "Dallas Cowboys", team: "DAL", position: "DST", default_price: 0)
# Player.create!(name: "Arizona Cardinals", team: "ARI", position: "DST", default_price: 0)
# Player.create!(name: "New York Jets", team: "NYJ", position: "DST", default_price: 0)
# Player.create!(name: "Chicago Bears", team: "CHI", position: "DST", default_price: 0)
# Player.create!(name: "Ian Thomas", team: "CAR", position: "TE", default_price: 0)
# Player.create!(name: "Jaylen Samuels", team: "PIT", position: "RB", default_price: 0)
# Player.create!(name: "Jerick McKinnon", team: "SF", position: "RB", default_price: 0)
# Player.create!(name: "Rex Burkhead", team: "NE", position: "RB", default_price: 0)
# Player.create!(name: "Gardner Minshew II", team: "JAC", position: "QB", default_price: 0)
# Player.create!(name: "Jimmy Garoppolo", team: "SF", position: "QB", default_price: 0)
# Player.create!(name: "Joe Burrow", team: "CIN", position: "QB", default_price: 0)
# Player.create!(name: "Drew Lock", team: "DEN", position: "QB", default_price: 0)
# Player.create!(name: "Justin Jefferson", team: "MIN", position: "WR", default_price: 2)
# Player.create!(name: "Mecole Hardman", team: "KC", position: "WR", default_price: 2)
# Player.create!(name: "Tennessee Titans", team: "TEN", position: "DST", default_price: 1)
# Player.create!(name: "Cincinnati Bengals", team: "CIN", position: "DST", default_price: 0)
# Player.create!(name: "New York Giants", team: "NYG", position: "DST", default_price: 0)
# Player.create!(name: "Las Vegas Raiders", team: "LV", position: "DST", default_price: 0)
# Player.create!(name: "Detroit Lions", team: "DET", position: "DST", default_price: 0)
# Player.create!(name: "Greg Olsen", team: "SEA", position: "TE", default_price: 0)
# Player.create!(name: "Miami Dolphins", team: "MIA", position: "DST", default_price: 0)
# Player.create!(name: "Los Angeles Chargers", team: "LAC", position: "DST", default_price: 0)
# Player.create!(name: "Atlanta Falcons", team: "ATL", position: "DST", default_price: 0)
# Player.create!(name: "Kyle Rudolph", team: "MIN", position: "TE", default_price: 0)
# Player.create(name: "Jace Sternberger", position: "TE", team: "GB", default_price: 0)
# Player.create(name: "Malcolm Brown", position: "RB", team: "LAR", default_price: 0)
# Player.create(name: "Anthony McFarland Jr", position: "RB", team: "PIT", default_price: 0)
# Player.create(name: "Rashaad Penny", position: "RB", team: "SEA", default_price: 0)
# Player.create(name: "Ryquell Armstead", position: "RB", team: "JAC", default_price: 0)
# Player.create(name: "Philip Rivers", position: "QB", team: "IND", default_price: 0)
# Player.create(name: "Teddy Bridgewater", position: "QB", team: "CAR", default_price: 0)
# Player.create(name: "Sam Darnold", position: "QB", team: "NYJ", default_price: 0)
# Player.create(name: "Dede Westbrook", position: "WR", team: "JAC", default_price: 0)
# Player.create(name: "Hunter Renfrow", position: "WR", team: "LV", default_price: 0)
# Player.create(name: "N'Keal Harry", position: "WR", team: "NE", default_price: 0)
# Player.create(name: "Corey Davis", position: "WR", team: "TEN", default_price: 0)
# Player.create(name: "Michael Pittman Jr", position: "WR", team: "IND", default_price: 0)
# Player.create(name: "Allen Lazard", position: "WR", team: "GB", default_price: 0)
# Player.create(name: "Irv Smith Jr", position: "TE", team: "MIN", default_price: 0)
# Player.create(name: "Dawson Knox", position: "TE", team: "BUF", default_price: 0)
# Player.create(name: "Dion Lewis", position: "RB", team: "NYG", default_price: 0)
# Player.create(name: "Carlos Hyde", position: "RB", team: "SEA", default_price: 0)
# Player.create(name: "Benny Snell Jr", position: "RB", team: "PIT", default_price: 0)
# Player.create(name: "Damien Harris", position: "RB", team: "NE", default_price: 0)
# Player.create(name: "Frank Gore", position: "RB", team: "NYJ", default_price: 0)
# Player.create(name: "Lynn Bowden Jr", position: "WR", team: "LV", default_price: 0)
# Player.create(name: "Derek Carr", position: "QB", team: "LV", default_price: 0)
# Player.create(name: "Tyrell Williams", position: "WR", team: "LV", default_price: 0)
# Player.create(name: "Danny Amendola", position: "WR", team: "DET", default_price: 0)
# Player.create(name: "Larry Fitzgerald", position: "WR", team: "ARI", default_price: 0)
# Player.create(name: "Steven Sims", position: "WR", team: "WAS", default_price: 0)
# Player.create(name: "Cole Beasley", position: "WR", team: "BUF", default_price: 0)
# Player.create(name: "Jimmy Graham", position: "TE", team: "CHI", default_price: 0)
# Player.create(name: "CJ Uzomah", position: "TE", team: "CIN", default_price: 0)
# Player.create(name: "Tyler Eifert", position: "TE", team: "JAC", default_price: 0)
# Player.create(name: "OJ Howard", position: "TE", team: "TB", default_price: 0)
# Player.create(name: "Royce Freeman", position: "RB", team: "DEN", default_price: 0)
# Player.create(name: "Gus Edwards", position: "RB", team: "BAL", default_price: 0)
# Player.create(name: "Reggie Bonnafon", position: "RB", team: "CAR", default_price: 0)
# Player.create(name: "Randal Cobb", position: "WR", team: "HOU", default_price: 0)
# Player.create(name: "Brandon Aiyuk", position: "WR", team: "SF", default_price: 0)
# Player.create(name: "Parris Campbell", position: "WR", team: "IND", default_price: 0)
# Player.create(name: "Denzel Mimms", position: 'WR', team: 'NYC', default_price: 0)
# Player.create(name: "Alshon Jeffery", position: "WR", team: "PHI", default_price: 0)
# Player.create(name: "Gerald Everett", position: "TE", team: "LAR", default_price: 0)
# Player.create(name: "David Njoku", position: "TE", team: "CLE", default_price: 0)
# Player.create(name: "Dare Ogunbowale", position: "RB", team: "TB", default_price: 0)
# Player.create(name: "Tee Higgins", position: "WR", team: "CIN", default_price: 0)
# Player.create(name: "Devin Funchess", position: "WR", team: "GB", default_price: 0)
# Player.create(name: "Mohammed Sanu", position: "WR", team: "NE", default_price: 0)
# Player.create(name: "Laviska Shenault Jr", position: "WR", team: "JAC", default_price: 0)
# Player.create(name: "John Ross", position: "WR", team: "CIN", default_price: 0)
# Player.create(name: "Dwayne Haskins", position: "QB", team: "WAS", default_price: 0)
# Player.create(name: "Nick Foles", position: "QB", team: "CHI", default_price: 0)
# Player.create(name: "Tua Tagovailoa", position: "QB", team: "MIA", default_price: 0)
# Player.create(name: "Tyrod Taylor", position: "QB", team: "LAC", default_price: 0)
# Player.create(name: "Ryan Fitzpatrick", position: "QB", team: "MIA", default_price: 0)
# Player.create(name: "Justin Herbert",position: "QB",team: "LAC", default_price: 0)
# Player.create(name: "Trent Taylor", position: "WR", team: "SF", default_price: 0)
# Player.create(name: "Dante Pettis", position: "WR", team: "SF", default_price: 0)


